<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Analisis Tasa de Intervencion</title>
  <meta name="description" content="Analisis Tasa de Intervencion" />
  <meta name="generator" content="bookdown 0.41 and GitBook 2.6.7" />

  <meta property="og:title" content="Analisis Tasa de Intervencion" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Analisis Tasa de Intervencion" />
  
  
  

<meta name="author" content="Gabriel Orozco/Diana Aguirre/Edgard Camacho" />


<meta name="date" content="2024-10-21" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  


<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Analisis Tasa de Intervencion</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path=""><a href="#enunciado"><i class="fa fa-check"></i><b>1</b> <strong>Enunciado:</strong></a>
<ul>
<li class="chapter" data-level="1.1" data-path=""><a href="#análisis-exploratorio"><i class="fa fa-check"></i><b>1.1</b> <strong>Análisis exploratorio:</strong></a></li>
<li class="chapter" data-level="1.2" data-path=""><a href="#gráficos-de-visualización"><i class="fa fa-check"></i><b>1.2</b> <strong>Gráficos de visualización:</strong></a></li>
<li class="chapter" data-level="1.3" data-path=""><a href="#análisis-de-serie-de-tiempo"><i class="fa fa-check"></i><b>1.3</b> <strong>Análisis de serie de tiempo:</strong></a>
<ul>
<li class="chapter" data-level="1.3.1" data-path=""><a href="#promedio-o-media-móvil"><i class="fa fa-check"></i><b>1.3.1</b> Promedio o media móvil</a></li>
<li class="chapter" data-level="1.3.2" data-path=""><a href="#rezago-operador-backshift-y-estacionalidad"><i class="fa fa-check"></i><b>1.3.2</b> Rezago (operador backshift) y estacionalidad</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path=""><a href="#fecha-vs-rezagos-lag-1-2-3"><i class="fa fa-check"></i><b>1.4</b> <strong>Fecha vs Rezagos (lag 1, 2, 3):</strong></a></li>
<li class="chapter" data-level="1.5" data-path=""><a href="#tasa-vs-rezagos-lag-1-2-3"><i class="fa fa-check"></i><b>1.5</b> <strong>Tasa vs Rezagos (lag 1, 2, 3):</strong></a></li>
<li class="chapter" data-level="1.6" data-path=""><a href="#promedio-movil-vs-rezagos-lag-1-2-3"><i class="fa fa-check"></i><b>1.6</b> <strong>Promedio Movil vs Rezagos (lag 1, 2, 3):</strong></a></li>
<li class="chapter" data-level="1.7" data-path=""><a href="#tasa-lag1-vs-rezagos"><i class="fa fa-check"></i><b>1.7</b> <strong>6. Tasa Lag1 vs Rezagos</strong></a>
<ul>
<li class="chapter" data-level="1.7.1" data-path=""><a href="#descomposición"><i class="fa fa-check"></i><b>1.7.1</b> Descomposición</a></li>
<li class="chapter" data-level="1.7.2" data-path=""><a href="#estacionariedad"><i class="fa fa-check"></i><b>1.7.2</b> Estacionariedad</a></li>
<li class="chapter" data-level="1.7.3" data-path=""><a href="#diferenciación"><i class="fa fa-check"></i><b>1.7.3</b> Diferenciación</a></li>
<li class="chapter" data-level="1.7.4" data-path=""><a href="#autocorrelación-acf-y-parcial-pacf"><i class="fa fa-check"></i><b>1.7.4</b> Autocorrelación (ACF) y Parcial (PACF)</a></li>
<li class="chapter" data-level="1.7.5" data-path=""><a href="#volver-a-verificar-la-estacionariedad-tras-la-diferenciación"><i class="fa fa-check"></i><b>1.7.5</b> Volver a verificar la Estacionariedad tras la Diferenciación</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Publicado con bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Analisis Tasa de Intervencion</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="header">
<h1 class="title">Analisis Tasa de Intervencion</h1>
<p class="author"><em>Gabriel Orozco/Diana Aguirre/Edgard Camacho</em></p>
<p class="date"><em>2024-10-21</em></p>
</div>
<div id="enunciado" class="section level1 hasAnchor" number="1">
<h1><span class="header-section-number">Capítulo: 1</span> <strong>Enunciado:</strong><a href="#enunciado" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>En este momento deberemos retomar la Unidad 1 en la cual se creó un minilibro que contiene el entregable de dicha unidad. Este documento tiene como repositorio GitHub (elaborado desde Markdown). Ahora, en esta Unidad 2, se debe continuar con los datos presentados en dicho entregable y se debe evidenciar, en una de las variables en el tiempo, la aproximación en promedio móvil, en rezagos y en estacionalidad. Todo lo anterior, a través de funciones y gráficas que permitan detectar patrones y ciclos de la variable.</p>
<div id="análisis-exploratorio" class="section level2 hasAnchor" number="1.1">
<h2><span class="header-section-number">1.1</span> <strong>Análisis exploratorio:</strong><a href="#análisis-exploratorio" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<pre><code>## tibble [310 × 2] (S3: tbl_df/tbl/data.frame)
##  $ Fecha: POSIXct[1:310], format: &quot;2024-10-01&quot; &quot;2024-09-01&quot; ...
##  $ Tasa : num [1:310] 10.2 10.8 10.8 11.8 11.8 ...</code></pre>
<p>Los datos representan una serie de tiempo de 310 filas y 2 columnas, correspondientes a la fecha y a la tasa. Se observa que la fecha realmente corresponde a un dato mensual por tanto conviene ajustar el formato.</p>
<pre><code>## # A tibble: 2 × 2
##   Fecha                Tasa
##   &lt;dttm&gt;              &lt;dbl&gt;
## 1 2024-10-01 00:00:00  10.2
## 2 1999-01-01 00:00:00  26</code></pre>
<p>Al consultar el primer y último registro del dataset, se identifica que la observación más reciente corresponde al mes de octubre de 2024 con una tasa de 10.25%, mientras que el registro más antiguo es de enero de 1999, con una tasa de 26%. Estos datos indican que el dataset abarca un período de aproximadamente 25 años (310 meses), desde finales del siglo XX hasta la fecha actual, reflejando un amplio intervalo temporal que podría incluir distintas tendencias o cambios económicos en la variable Tasa.</p>
<pre><code>##      Fecha                             Tasa       
##  Min.   :1999-01-01 00:00:00.00   Min.   : 1.750  
##  1st Qu.:2005-06-08 12:00:00.00   1st Qu.: 4.250  
##  Median :2011-11-16 00:00:00.00   Median : 6.000  
##  Mean   :2011-11-16 00:18:34.83   Mean   : 6.957  
##  3rd Qu.:2018-04-23 12:00:00.00   3rd Qu.: 9.250  
##  Max.   :2024-10-01 00:00:00.00   Max.   :26.000</code></pre>
<ul>
<li>La serie cubre un rango de 25 años, con la mediana alrededor de 2011, lo que sugiere que los datos están relativamente bien distribuidos a lo largo del tiempo.</li>
<li>La tasa tiene una amplia variabilidad, con un valor mínimo de 1.75 y un máximo de 26. La mayor parte de los valores se concentran entre 4.25 y 9.25 (entre el primer y tercer cuartil).</li>
</ul>
<p>No se identifican datos ausentes:</p>
<pre><code>## Fecha  Tasa 
##     0     0</code></pre>
<p>Con el código siguiente, se agregan dos columnas adicionales, llamadas <strong>Anio</strong> y <strong>Mes</strong>, lo anterior para poder tener una mejor visual de los datos, teniendo en cuenta el gran número de registros que tiene el dataset.</p>
<pre><code>## # A tibble: 6 × 4
##    Anio Mes   Fecha       Tasa
##   &lt;dbl&gt; &lt;ord&gt; &lt;date&gt;     &lt;dbl&gt;
## 1  2024 oct   2024-10-01  10.2
## 2  2024 sept  2024-09-01  10.8
## 3  2024 ago   2024-08-01  10.8
## 4  2024 jul   2024-07-01  11.8
## 5  2024 jun   2024-06-01  11.8
## 6  2024 may   2024-05-01  12.2</code></pre>
</div>
<div id="gráficos-de-visualización" class="section level2 hasAnchor" number="1.2">
<h2><span class="header-section-number">1.2</span> <strong>Gráficos de visualización:</strong><a href="#gráficos-de-visualización" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<pre><code>## `geom_smooth()` using formula = &#39;y ~ x&#39;</code></pre>
<p><img src="index_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<ul>
<li><p><strong>Puntos Azules:</strong> Los puntos azules indican los valores de “Tasa” en momentos específicos. Hay una dispersión considerable, sugiriendo que la tasa ha experimentado fluctuaciones a lo largo del tiempo.</p></li>
<li><p><strong>Línea Roja:</strong> Esta línea es el resultado de un ajuste de suavización (usando el método LOESS). La línea roja ilustra la tendencia general de la “Tasa” a lo largo del tiempo. A partir de la línea, se puede observar que, aunque hay variaciones, existe una tendencia que se puede analizar para hacer predicciones o entender mejor el comportamiento de la variable.</p></li>
<li><p><strong>Variaciones:</strong> La gráfica muestra que la Tasa ha tenido picos y valles, lo que podría indicar variaciones estacionales o influencias externas que afectan la variable a lo largo del tiempo. A partir de la línea de suavización, parece que la Tasa ha ido disminuyendo o estabilizándose en ciertos períodos, teniendo una caída significativa desde 1999 hasta 2003, y un aumento importante de 2021 a 2024.</p></li>
</ul>
<pre><code>## `geom_smooth()` using formula = &#39;y ~ x&#39;</code></pre>
<p><img src="index_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<p>Esta gráfica permite ver con más detalle los cambios de tendencia:</p>
<ul>
<li><p>Desde 1999, se confirma la disminución significativa en la tasa, que empieza muy alta (cerca de 25) y cae rápidamente hasta estabilizarse alrededor de los años 2007-2008 en un valor muy inferior (por debajo de 10).</p></li>
<li><p>Entre 2005 y 2020, se observan picos y caídas a intervalos relativamente regulares, pero sin grandes cambios en los niveles generales hasta el repunte final.</p></li>
<li><p>Eentre 2010 y 2020, la tasa se mantiene más estable, con algunas oscilaciones en torno a los 5-10 puntos.</p></li>
<li><p>A partir de 2021, hay una tendencia de aumento, que se hace más pronunciada hacia los años más recientes. Esto podría ser consecuencia de algún cambio en las políticas o factores externos como la pandemia de COVID-19.</p></li>
<li><p>La línea de tendencia suavizada indica una caída rápida, seguida de un periodo de estabilización, y finalmente una tendencia de aumento en los años recientes, semejando una forma de “U” suavizada.</p></li>
</ul>
<pre><code>## `summarise()` has grouped output by &#39;Anio&#39;. You can override using the
## `.groups` argument.</code></pre>
<table class="table" style="width: auto !important; ">
<thead>
<tr>
<th style="text-align:right;">
Anio
</th>
<th style="text-align:right;">
ene
</th>
<th style="text-align:right;">
feb
</th>
<th style="text-align:right;">
mar
</th>
<th style="text-align:right;">
abr
</th>
<th style="text-align:right;">
may
</th>
<th style="text-align:right;">
jun
</th>
<th style="text-align:right;">
jul
</th>
<th style="text-align:right;">
ago
</th>
<th style="text-align:right;">
sept
</th>
<th style="text-align:right;">
oct
</th>
<th style="text-align:right;">
nov
</th>
<th style="text-align:right;">
dic
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
1999
</td>
<td style="text-align:right;">
26.0
</td>
<td style="text-align:right;">
26.0
</td>
<td style="text-align:right;">
24.0
</td>
<td style="text-align:right;">
20.0
</td>
<td style="text-align:right;">
19.0
</td>
<td style="text-align:right;">
18.0
</td>
<td style="text-align:right;">
18.0
</td>
<td style="text-align:right;">
17.0
</td>
<td style="text-align:right;">
16.0
</td>
<td style="text-align:right;">
16.0
</td>
<td style="text-align:right;">
15.0
</td>
<td style="text-align:right;">
13.0
</td>
</tr>
<tr>
<td style="text-align:right;">
2000
</td>
<td style="text-align:right;">
12.0
</td>
<td style="text-align:right;">
12.0
</td>
<td style="text-align:right;">
12.0
</td>
<td style="text-align:right;">
12.0
</td>
<td style="text-align:right;">
12.0
</td>
<td style="text-align:right;">
12.0
</td>
<td style="text-align:right;">
12.0
</td>
<td style="text-align:right;">
12.0
</td>
<td style="text-align:right;">
12.0
</td>
<td style="text-align:right;">
12.0
</td>
<td style="text-align:right;">
12.0
</td>
<td style="text-align:right;">
12.0
</td>
</tr>
<tr>
<td style="text-align:right;">
2001
</td>
<td style="text-align:right;">
12.0
</td>
<td style="text-align:right;">
12.0
</td>
<td style="text-align:right;">
12.0
</td>
<td style="text-align:right;">
11.5
</td>
<td style="text-align:right;">
11.5
</td>
<td style="text-align:right;">
11.5
</td>
<td style="text-align:right;">
11.5
</td>
<td style="text-align:right;">
11.0
</td>
<td style="text-align:right;">
10.0
</td>
<td style="text-align:right;">
9.5
</td>
<td style="text-align:right;">
9.2
</td>
<td style="text-align:right;">
8.8
</td>
</tr>
<tr>
<td style="text-align:right;">
2002
</td>
<td style="text-align:right;">
8.5
</td>
<td style="text-align:right;">
8.0
</td>
<td style="text-align:right;">
8.0
</td>
<td style="text-align:right;">
7.2
</td>
<td style="text-align:right;">
6.2
</td>
<td style="text-align:right;">
5.8
</td>
<td style="text-align:right;">
5.2
</td>
<td style="text-align:right;">
5.2
</td>
<td style="text-align:right;">
5.2
</td>
<td style="text-align:right;">
5.2
</td>
<td style="text-align:right;">
5.2
</td>
<td style="text-align:right;">
5.2
</td>
</tr>
<tr>
<td style="text-align:right;">
2003
</td>
<td style="text-align:right;">
5.2
</td>
<td style="text-align:right;">
6.2
</td>
<td style="text-align:right;">
6.2
</td>
<td style="text-align:right;">
6.2
</td>
<td style="text-align:right;">
7.2
</td>
<td style="text-align:right;">
7.2
</td>
<td style="text-align:right;">
7.2
</td>
<td style="text-align:right;">
7.2
</td>
<td style="text-align:right;">
7.2
</td>
<td style="text-align:right;">
7.2
</td>
<td style="text-align:right;">
7.2
</td>
<td style="text-align:right;">
7.2
</td>
</tr>
<tr>
<td style="text-align:right;">
2004
</td>
<td style="text-align:right;">
7.2
</td>
<td style="text-align:right;">
7.2
</td>
<td style="text-align:right;">
7.0
</td>
<td style="text-align:right;">
6.8
</td>
<td style="text-align:right;">
6.8
</td>
<td style="text-align:right;">
6.8
</td>
<td style="text-align:right;">
6.8
</td>
<td style="text-align:right;">
6.8
</td>
<td style="text-align:right;">
6.8
</td>
<td style="text-align:right;">
6.8
</td>
<td style="text-align:right;">
6.8
</td>
<td style="text-align:right;">
6.8
</td>
</tr>
<tr>
<td style="text-align:right;">
2005
</td>
<td style="text-align:right;">
6.5
</td>
<td style="text-align:right;">
6.5
</td>
<td style="text-align:right;">
6.5
</td>
<td style="text-align:right;">
6.5
</td>
<td style="text-align:right;">
6.5
</td>
<td style="text-align:right;">
6.5
</td>
<td style="text-align:right;">
6.5
</td>
<td style="text-align:right;">
6.5
</td>
<td style="text-align:right;">
6.5
</td>
<td style="text-align:right;">
6.0
</td>
<td style="text-align:right;">
6.0
</td>
<td style="text-align:right;">
6.0
</td>
</tr>
<tr>
<td style="text-align:right;">
2006
</td>
<td style="text-align:right;">
6.0
</td>
<td style="text-align:right;">
6.0
</td>
<td style="text-align:right;">
6.0
</td>
<td style="text-align:right;">
6.0
</td>
<td style="text-align:right;">
6.0
</td>
<td style="text-align:right;">
6.2
</td>
<td style="text-align:right;">
6.5
</td>
<td style="text-align:right;">
6.5
</td>
<td style="text-align:right;">
6.8
</td>
<td style="text-align:right;">
6.8
</td>
<td style="text-align:right;">
7.2
</td>
<td style="text-align:right;">
7.2
</td>
</tr>
<tr>
<td style="text-align:right;">
2007
</td>
<td style="text-align:right;">
7.5
</td>
<td style="text-align:right;">
7.8
</td>
<td style="text-align:right;">
8.0
</td>
<td style="text-align:right;">
8.2
</td>
<td style="text-align:right;">
8.2
</td>
<td style="text-align:right;">
8.8
</td>
<td style="text-align:right;">
9.0
</td>
<td style="text-align:right;">
9.2
</td>
<td style="text-align:right;">
9.2
</td>
<td style="text-align:right;">
9.2
</td>
<td style="text-align:right;">
9.2
</td>
<td style="text-align:right;">
9.5
</td>
</tr>
<tr>
<td style="text-align:right;">
2008
</td>
<td style="text-align:right;">
9.5
</td>
<td style="text-align:right;">
9.5
</td>
<td style="text-align:right;">
9.8
</td>
<td style="text-align:right;">
9.8
</td>
<td style="text-align:right;">
9.8
</td>
<td style="text-align:right;">
9.8
</td>
<td style="text-align:right;">
9.8
</td>
<td style="text-align:right;">
10.0
</td>
<td style="text-align:right;">
10.0
</td>
<td style="text-align:right;">
10.0
</td>
<td style="text-align:right;">
10.0
</td>
<td style="text-align:right;">
10.0
</td>
</tr>
<tr>
<td style="text-align:right;">
2009
</td>
<td style="text-align:right;">
9.5
</td>
<td style="text-align:right;">
9.5
</td>
<td style="text-align:right;">
9.0
</td>
<td style="text-align:right;">
7.0
</td>
<td style="text-align:right;">
7.0
</td>
<td style="text-align:right;">
5.0
</td>
<td style="text-align:right;">
4.5
</td>
<td style="text-align:right;">
4.5
</td>
<td style="text-align:right;">
4.5
</td>
<td style="text-align:right;">
4.0
</td>
<td style="text-align:right;">
4.0
</td>
<td style="text-align:right;">
3.5
</td>
</tr>
<tr>
<td style="text-align:right;">
2010
</td>
<td style="text-align:right;">
3.5
</td>
<td style="text-align:right;">
3.5
</td>
<td style="text-align:right;">
3.5
</td>
<td style="text-align:right;">
3.5
</td>
<td style="text-align:right;">
3.5
</td>
<td style="text-align:right;">
3.0
</td>
<td style="text-align:right;">
3.0
</td>
<td style="text-align:right;">
3.0
</td>
<td style="text-align:right;">
3.0
</td>
<td style="text-align:right;">
3.0
</td>
<td style="text-align:right;">
3.0
</td>
<td style="text-align:right;">
3.0
</td>
</tr>
<tr>
<td style="text-align:right;">
2011
</td>
<td style="text-align:right;">
3.0
</td>
<td style="text-align:right;">
3.0
</td>
<td style="text-align:right;">
3.2
</td>
<td style="text-align:right;">
3.5
</td>
<td style="text-align:right;">
3.5
</td>
<td style="text-align:right;">
4.0
</td>
<td style="text-align:right;">
4.2
</td>
<td style="text-align:right;">
4.5
</td>
<td style="text-align:right;">
4.5
</td>
<td style="text-align:right;">
4.5
</td>
<td style="text-align:right;">
4.5
</td>
<td style="text-align:right;">
4.8
</td>
</tr>
<tr>
<td style="text-align:right;">
2012
</td>
<td style="text-align:right;">
4.8
</td>
<td style="text-align:right;">
5.0
</td>
<td style="text-align:right;">
5.2
</td>
<td style="text-align:right;">
5.2
</td>
<td style="text-align:right;">
5.2
</td>
<td style="text-align:right;">
5.2
</td>
<td style="text-align:right;">
5.2
</td>
<td style="text-align:right;">
5.0
</td>
<td style="text-align:right;">
4.8
</td>
<td style="text-align:right;">
4.8
</td>
<td style="text-align:right;">
4.8
</td>
<td style="text-align:right;">
4.5
</td>
</tr>
<tr>
<td style="text-align:right;">
2013
</td>
<td style="text-align:right;">
4.2
</td>
<td style="text-align:right;">
4.0
</td>
<td style="text-align:right;">
3.8
</td>
<td style="text-align:right;">
3.2
</td>
<td style="text-align:right;">
3.2
</td>
<td style="text-align:right;">
3.2
</td>
<td style="text-align:right;">
3.2
</td>
<td style="text-align:right;">
3.2
</td>
<td style="text-align:right;">
3.2
</td>
<td style="text-align:right;">
3.2
</td>
<td style="text-align:right;">
3.2
</td>
<td style="text-align:right;">
3.2
</td>
</tr>
<tr>
<td style="text-align:right;">
2014
</td>
<td style="text-align:right;">
3.2
</td>
<td style="text-align:right;">
3.2
</td>
<td style="text-align:right;">
3.2
</td>
<td style="text-align:right;">
3.2
</td>
<td style="text-align:right;">
3.5
</td>
<td style="text-align:right;">
3.5
</td>
<td style="text-align:right;">
4.0
</td>
<td style="text-align:right;">
4.2
</td>
<td style="text-align:right;">
4.5
</td>
<td style="text-align:right;">
4.5
</td>
<td style="text-align:right;">
4.5
</td>
<td style="text-align:right;">
4.5
</td>
</tr>
<tr>
<td style="text-align:right;">
2015
</td>
<td style="text-align:right;">
4.5
</td>
<td style="text-align:right;">
4.5
</td>
<td style="text-align:right;">
4.5
</td>
<td style="text-align:right;">
4.5
</td>
<td style="text-align:right;">
4.5
</td>
<td style="text-align:right;">
4.5
</td>
<td style="text-align:right;">
4.5
</td>
<td style="text-align:right;">
4.5
</td>
<td style="text-align:right;">
4.5
</td>
<td style="text-align:right;">
4.8
</td>
<td style="text-align:right;">
4.8
</td>
<td style="text-align:right;">
5.5
</td>
</tr>
<tr>
<td style="text-align:right;">
2016
</td>
<td style="text-align:right;">
5.8
</td>
<td style="text-align:right;">
6.0
</td>
<td style="text-align:right;">
6.2
</td>
<td style="text-align:right;">
6.5
</td>
<td style="text-align:right;">
6.5
</td>
<td style="text-align:right;">
7.2
</td>
<td style="text-align:right;">
7.5
</td>
<td style="text-align:right;">
7.8
</td>
<td style="text-align:right;">
7.8
</td>
<td style="text-align:right;">
7.8
</td>
<td style="text-align:right;">
7.8
</td>
<td style="text-align:right;">
7.8
</td>
</tr>
<tr>
<td style="text-align:right;">
2017
</td>
<td style="text-align:right;">
7.5
</td>
<td style="text-align:right;">
7.5
</td>
<td style="text-align:right;">
7.2
</td>
<td style="text-align:right;">
7.0
</td>
<td style="text-align:right;">
7.0
</td>
<td style="text-align:right;">
6.2
</td>
<td style="text-align:right;">
6.2
</td>
<td style="text-align:right;">
5.5
</td>
<td style="text-align:right;">
5.2
</td>
<td style="text-align:right;">
5.2
</td>
<td style="text-align:right;">
5.0
</td>
<td style="text-align:right;">
4.8
</td>
</tr>
<tr>
<td style="text-align:right;">
2018
</td>
<td style="text-align:right;">
4.8
</td>
<td style="text-align:right;">
4.5
</td>
<td style="text-align:right;">
4.5
</td>
<td style="text-align:right;">
4.5
</td>
<td style="text-align:right;">
4.2
</td>
<td style="text-align:right;">
4.2
</td>
<td style="text-align:right;">
4.2
</td>
<td style="text-align:right;">
4.2
</td>
<td style="text-align:right;">
4.2
</td>
<td style="text-align:right;">
4.2
</td>
<td style="text-align:right;">
4.2
</td>
<td style="text-align:right;">
4.2
</td>
</tr>
<tr>
<td style="text-align:right;">
2019
</td>
<td style="text-align:right;">
4.2
</td>
<td style="text-align:right;">
4.2
</td>
<td style="text-align:right;">
4.2
</td>
<td style="text-align:right;">
4.2
</td>
<td style="text-align:right;">
4.2
</td>
<td style="text-align:right;">
4.2
</td>
<td style="text-align:right;">
4.2
</td>
<td style="text-align:right;">
4.2
</td>
<td style="text-align:right;">
4.2
</td>
<td style="text-align:right;">
4.2
</td>
<td style="text-align:right;">
4.2
</td>
<td style="text-align:right;">
4.2
</td>
</tr>
<tr>
<td style="text-align:right;">
2020
</td>
<td style="text-align:right;">
4.2
</td>
<td style="text-align:right;">
4.2
</td>
<td style="text-align:right;">
4.2
</td>
<td style="text-align:right;">
3.8
</td>
<td style="text-align:right;">
3.8
</td>
<td style="text-align:right;">
2.8
</td>
<td style="text-align:right;">
2.5
</td>
<td style="text-align:right;">
2.5
</td>
<td style="text-align:right;">
2.0
</td>
<td style="text-align:right;">
1.8
</td>
<td style="text-align:right;">
1.8
</td>
<td style="text-align:right;">
1.8
</td>
</tr>
<tr>
<td style="text-align:right;">
2021
</td>
<td style="text-align:right;">
1.8
</td>
<td style="text-align:right;">
1.8
</td>
<td style="text-align:right;">
1.8
</td>
<td style="text-align:right;">
1.8
</td>
<td style="text-align:right;">
1.8
</td>
<td style="text-align:right;">
1.8
</td>
<td style="text-align:right;">
1.8
</td>
<td style="text-align:right;">
1.8
</td>
<td style="text-align:right;">
1.8
</td>
<td style="text-align:right;">
2.0
</td>
<td style="text-align:right;">
2.0
</td>
<td style="text-align:right;">
2.5
</td>
</tr>
<tr>
<td style="text-align:right;">
2022
</td>
<td style="text-align:right;">
3.0
</td>
<td style="text-align:right;">
4.0
</td>
<td style="text-align:right;">
4.0
</td>
<td style="text-align:right;">
5.0
</td>
<td style="text-align:right;">
5.0
</td>
<td style="text-align:right;">
6.0
</td>
<td style="text-align:right;">
7.5
</td>
<td style="text-align:right;">
9.0
</td>
<td style="text-align:right;">
9.0
</td>
<td style="text-align:right;">
10.0
</td>
<td style="text-align:right;">
11.0
</td>
<td style="text-align:right;">
11.0
</td>
</tr>
<tr>
<td style="text-align:right;">
2023
</td>
<td style="text-align:right;">
12.0
</td>
<td style="text-align:right;">
12.8
</td>
<td style="text-align:right;">
12.8
</td>
<td style="text-align:right;">
13.0
</td>
<td style="text-align:right;">
13.0
</td>
<td style="text-align:right;">
13.2
</td>
<td style="text-align:right;">
13.2
</td>
<td style="text-align:right;">
13.2
</td>
<td style="text-align:right;">
13.2
</td>
<td style="text-align:right;">
13.2
</td>
<td style="text-align:right;">
13.2
</td>
<td style="text-align:right;">
13.2
</td>
</tr>
<tr>
<td style="text-align:right;">
2024
</td>
<td style="text-align:right;">
13.0
</td>
<td style="text-align:right;">
12.8
</td>
<td style="text-align:right;">
12.8
</td>
<td style="text-align:right;">
12.2
</td>
<td style="text-align:right;">
12.2
</td>
<td style="text-align:right;">
11.8
</td>
<td style="text-align:right;">
11.8
</td>
<td style="text-align:right;">
10.8
</td>
<td style="text-align:right;">
10.8
</td>
<td style="text-align:right;">
10.2
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
NA
</td>
</tr>
</tbody>
</table>
<p>A partir de la tabla se pueden confirmar las tendencias mencionadas anteriormente, con un comportamiento descendente en los 12 primeros años (1999 a 2010), una estabilización en los 5 años siguientes (2011-2015) y un incremento significativo en años recientes (2021 en adelante).</p>
</div>
<div id="análisis-de-serie-de-tiempo" class="section level2 hasAnchor" number="1.3">
<h2><span class="header-section-number">1.3</span> <strong>Análisis de serie de tiempo:</strong><a href="#análisis-de-serie-de-tiempo" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="promedio-o-media-móvil" class="section level3 hasAnchor" number="1.3.1">
<h3><span class="header-section-number">1.3.1</span> Promedio o media móvil<a href="#promedio-o-media-móvil" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Permite analizar el mercado a través de las tendencias. La media móvil es una técnica estadística que se utiliza para analizar datos a lo largo del tiempo. Permite calcular la media de un conjunto de valores en un intervalo específico y luego desplazar ese intervalo a lo largo de la serie de datos para obtener una nueva serie de medias; lo que permite suavizar fluctuaciones en los datos así como resaltar tendencias.</p>
<p>Se conoce como media móvil ya que el valor se calcula constantemente a medida que pasa el tiempo; de esta forma, la media cambia cada vez que los valores presentan alguna modificación.</p>
<p><img src="index_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
</div>
<div id="rezago-operador-backshift-y-estacionalidad" class="section level3 hasAnchor" number="1.3.2">
<h3><span class="header-section-number">1.3.2</span> Rezago (operador backshift) y estacionalidad<a href="#rezago-operador-backshift-y-estacionalidad" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>El rezago es una herramienta estadística para el análisis de series temporales, que permite observar el valor de una variable en un momento anterior, facilitando la identificación de patrones y tendencias a lo largo del tiempo.</p>
<p>En cuanto a la estacionalidad, hace referencia a las variaciones periódicas y predecibles en los datos que ocurren en intervalos regulares.</p>
<p>Con la incorporación de ambas herramientas es posible modelar y prever comportamientos futuros de las series temporales.</p>
<pre><code>## # A tibble: 6 × 6
##    Anio Mes   Fecha       Tasa PromedioMovil Tasa_lag1
##   &lt;dbl&gt; &lt;ord&gt; &lt;date&gt;     &lt;dbl&gt;         &lt;dbl&gt;     &lt;dbl&gt;
## 1  2024 oct   2024-10-01  10.2          NA        NA  
## 2  2024 sept  2024-09-01  10.8          NA        10.2
## 3  2024 ago   2024-08-01  10.8          10.6      10.8
## 4  2024 jul   2024-07-01  11.8          11.1      10.8
## 5  2024 jun   2024-06-01  11.8          11.4      11.8
## 6  2024 may   2024-05-01  12.2          11.9      11.8</code></pre>
<p><img src="index_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
<p>La gráfica visualiza la correlación entre una variable y sus valores rezagados (delayed values). Este gráfico es útil para detectar patrones en series temporales y evaluar la autocorrelación en los datos.</p>
<ul>
<li><strong>1. Año vs Rezagos (lag 1, 2, 3)</strong></li>
</ul>
<p>Las gráficas entre Año y sus diferentes rezagos muestran una relación lineal perfecta, lo que era de esperarse, ya que el valor de un año en un rezago anterior está directamente relacionado con los años consecutivos. Esto sugiere que el “Año” no aporta una variabilidad significativa en términos de cambios bruscos, es decir, la serie avanza sin saltos.</p>
<ul>
<li><strong>2. Mes vs Rezagos (lag 1, 2, 3)</strong></li>
</ul>
<p>Las gráficas entre Mes y sus rezagos muestran una estructura cíclica, con puntos que siguen un patrón predecible. Esto tiene sentido, ya que los meses siguen un ciclo repetitivo de 12 unidades (de enero a diciembre).</p>
<p>los meses correlacionan bien con sus rezagos inmediatos, pero a medida que aumenta el número de rezagos (lag 2, lag 3), el ciclo es más visible, lo que indica que la periodicidad estacional en los datos está bien representada.</p>
</div>
</div>
<div id="fecha-vs-rezagos-lag-1-2-3" class="section level2 hasAnchor" number="1.4">
<h2><span class="header-section-number">1.4</span> <strong>Fecha vs Rezagos (lag 1, 2, 3):</strong><a href="#fecha-vs-rezagos-lag-1-2-3" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Similar al año, la relación entre Fecha y sus rezagos también muestra una estructura lineal. Esto era previsible, ya que las fechas están organizadas de manera continua. No se observan cambios abruptos o interrupciones que puedan señalar eventos singulares en la serie temporal.</p>
</div>
<div id="tasa-vs-rezagos-lag-1-2-3" class="section level2 hasAnchor" number="1.5">
<h2><span class="header-section-number">1.5</span> <strong>Tasa vs Rezagos (lag 1, 2, 3):</strong><a href="#tasa-vs-rezagos-lag-1-2-3" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>En las gráficas entre Tasa y sus rezagos, especialmente en el rezago 1 (lag 1), se aprecia una clara correlación positiva, lo que significa que la tasa en un mes está fuertemente relacionada con la tasa del mes anterior. Esta relación indica una persistencia en la tasa, es decir, no hay cambios abruptos entre periodos consecutivos.</p>
<p>A medida que el rezago aumenta (lag 2 y lag 3), la relación sigue siendo positiva pero disminuye levemente, lo cual es normal: los valores más distantes en el tiempo tienen menos influencia directa entre sí, aunque todavía se observa cierta correlación.</p>
<p>Esto sugiere que la serie de tasas no presenta grandes fluctuaciones a corto plazo y que los valores siguen un comportamiento más estable, lo que puede indicar una tendencia suave sin variaciones abruptas.</p>
</div>
<div id="promedio-movil-vs-rezagos-lag-1-2-3" class="section level2 hasAnchor" number="1.6">
<h2><span class="header-section-number">1.6</span> <strong>Promedio Movil vs Rezagos (lag 1, 2, 3):</strong><a href="#promedio-movil-vs-rezagos-lag-1-2-3" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Similar a la “Tasa”, las gráficas entre el Promedio Móvil y sus rezagos muestran una alta correlación, especialmente para lag 1. Esto sugiere que los promedios móviles no cambian drásticamente de un mes a otro, y los valores del promedio móvil están fuertemente ligados a los meses anteriores. A medida que aumenta el rezago (lag 2, lag 3), la correlación disminuye ligeramente, lo que indica que los valores anteriores siguen teniendo una influencia pero con una menor magnitud.</p>
</div>
<div id="tasa-lag1-vs-rezagos" class="section level2 hasAnchor" number="1.7">
<h2><span class="header-section-number">1.7</span> <strong>6. Tasa Lag1 vs Rezagos</strong><a href="#tasa-lag1-vs-rezagos" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Las gráficas entre Tasa_lag1 y sus rezagos también muestran una alta correlación. Esto es de esperar, ya que los valores rezagados de una variable tienden a mostrar correlación fuerte con rezagos cercanos.</p>
<p>Los gráficos de rezago muestran una clara autocorrelación tanto en las variables de Tasa como en el Promedio Móvil, lo que sugiere que los valores actuales están muy influenciados por sus valores anteriores.</p>
<p>No se observan grandes fluctuaciones o cambios abruptos en la serie temporal, lo que implica que los datos de tasa y promedio móvil siguen una evolución suave a lo largo del tiempo.</p>
<p>La estructura cíclica en los meses sugiere que existe un patrón estacional predecible, lo cual es clave para definir modelos de predicción de series temporales con componentes estacionales, como modelos ARIMA/SARIMA o de descomposición estacional.</p>
<hr />
<p>Descomposición: Con la función stl(), se descompone la serie en tendencia, estacionalidad y componente residual.</p>
<p>Estacionariedad: La prueba ADF indica si la serie tiene una raíz unitaria (es decir, si no es estacionaria).</p>
<p>Diferenciación: Si la serie no es estacionaria, la diferenciación la ayuda a volverse estacionaria.</p>
<div id="descomposición" class="section level3 hasAnchor" number="1.7.1">
<h3><span class="header-section-number">1.7.1</span> Descomposición<a href="#descomposición" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><img src="index_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
</div>
<div id="estacionariedad" class="section level3 hasAnchor" number="1.7.2">
<h3><span class="header-section-number">1.7.2</span> Estacionariedad<a href="#estacionariedad" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<pre><code>## 
##  Augmented Dickey-Fuller Test
## 
## data:  ts_data
## Dickey-Fuller = -1.15, Lag order = 6, p-value = 0.9133
## alternative hypothesis: stationary</code></pre>
</div>
<div id="diferenciación" class="section level3 hasAnchor" number="1.7.3">
<h3><span class="header-section-number">1.7.3</span> Diferenciación<a href="#diferenciación" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><img src="index_files/figure-html/unnamed-chunk-17-1.png" width="672" /></p>
</div>
<div id="autocorrelación-acf-y-parcial-pacf" class="section level3 hasAnchor" number="1.7.4">
<h3><span class="header-section-number">1.7.4</span> Autocorrelación (ACF) y Parcial (PACF)<a href="#autocorrelación-acf-y-parcial-pacf" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<pre><code>## [1] &quot;Anio&quot;          &quot;Mes&quot;           &quot;Fecha&quot;         &quot;Tasa&quot;         
## [5] &quot;PromedioMovil&quot; &quot;Tasa_lag1&quot;</code></pre>
<pre><code>## [1] &quot;Fecha&quot; &quot;Tasa&quot;</code></pre>
<p><img src="index_files/figure-html/unnamed-chunk-18-1.png" width="672" /></p>
</div>
<div id="volver-a-verificar-la-estacionariedad-tras-la-diferenciación" class="section level3 hasAnchor" number="1.7.5">
<h3><span class="header-section-number">1.7.5</span> Volver a verificar la Estacionariedad tras la Diferenciación<a href="#volver-a-verificar-la-estacionariedad-tras-la-diferenciación" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<pre><code>## 
##  Augmented Dickey-Fuller Test
## 
## data:  differenced_data
## Dickey-Fuller = -3.0792, Lag order = 6, p-value = 0.1214
## alternative hypothesis: stationary</code></pre>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" tabindex="-1"></a><span class="fu">library</span>(forecast) <span class="co"># Para el modelado ARIMA</span></span>
<span id="cb14-2"><a href="#cb14-2" tabindex="-1"></a></span>
<span id="cb14-3"><a href="#cb14-3" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">colnames</span>(data2))  </span></code></pre></div>
<pre><code>## [1] &quot;Anio&quot;          &quot;Mes&quot;           &quot;Fecha&quot;         &quot;Tasa&quot;         
## [5] &quot;PromedioMovil&quot; &quot;Tasa_lag1&quot;</code></pre>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" tabindex="-1"></a>ts_data <span class="ot">&lt;-</span> <span class="fu">ts</span>(data2[[<span class="st">&quot;Tasa&quot;</span>]], <span class="at">start =</span> <span class="fu">c</span>(<span class="dv">1999</span>, <span class="dv">1</span>), <span class="at">frequency =</span> <span class="dv">12</span>)</span>
<span id="cb16-2"><a href="#cb16-2" tabindex="-1"></a></span>
<span id="cb16-3"><a href="#cb16-3" tabindex="-1"></a><span class="co"># Graficar ACF y PACF</span></span>
<span id="cb16-4"><a href="#cb16-4" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>))</span>
<span id="cb16-5"><a href="#cb16-5" tabindex="-1"></a></span>
<span id="cb16-6"><a href="#cb16-6" tabindex="-1"></a><span class="co"># Graficar ACF</span></span>
<span id="cb16-7"><a href="#cb16-7" tabindex="-1"></a><span class="co">#acf(ts_data, main = &quot;ACF de la Serie Original&quot;)</span></span>
<span id="cb16-8"><a href="#cb16-8" tabindex="-1"></a></span>
<span id="cb16-9"><a href="#cb16-9" tabindex="-1"></a><span class="co"># Graficar PACF</span></span>
<span id="cb16-10"><a href="#cb16-10" tabindex="-1"></a><span class="co">#pacf(ts_data, main = &quot;PACF de la Serie Original&quot;)</span></span>
<span id="cb16-11"><a href="#cb16-11" tabindex="-1"></a></span>
<span id="cb16-12"><a href="#cb16-12" tabindex="-1"></a><span class="co"># Ajustar el modelo ARIMA(0,0,3)(0,0,1)[12]</span></span>
<span id="cb16-13"><a href="#cb16-13" tabindex="-1"></a>modelo_arima <span class="ot">&lt;-</span> <span class="fu">Arima</span>(ts_data, <span class="at">order =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">3</span>), <span class="at">seasonal =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">1</span>))</span>
<span id="cb16-14"><a href="#cb16-14" tabindex="-1"></a></span>
<span id="cb16-15"><a href="#cb16-15" tabindex="-1"></a><span class="co"># Resumen del modelo ajustado</span></span>
<span id="cb16-16"><a href="#cb16-16" tabindex="-1"></a><span class="fu">summary</span>(modelo_arima)</span></code></pre></div>
<pre><code>## Series: ts_data 
## ARIMA(0,0,3)(0,0,1)[12] with non-zero mean 
## 
## Coefficients:
##          ma1     ma2     ma3    sma1    mean
##       1.7171  1.6105  0.7743  0.5829  7.3301
## s.e.  0.0381  0.0479  0.0376  0.0502  0.3817
## 
## sigma^2 = 0.724:  log likelihood = -389.13
## AIC=790.27   AICc=790.55   BIC=812.65
## 
## Training set error measures:
##                        ME      RMSE       MAE       MPE     MAPE      MASE
## Training set -0.009182104 0.8439211 0.5782735 -5.077274 10.40789 0.2748598
##                  ACF1
## Training set 0.364348</code></pre>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" tabindex="-1"></a><span class="co"># Graficar los residuos</span></span>
<span id="cb18-2"><a href="#cb18-2" tabindex="-1"></a><span class="fu">checkresiduals</span>(modelo_arima)</span></code></pre></div>
<p><img src="index_files/figure-html/unnamed-chunk-20-1.png" width="672" /></p>
<pre><code>## 
##  Ljung-Box test
## 
## data:  Residuals from ARIMA(0,0,3)(0,0,1)[12] with non-zero mean
## Q* = 604.63, df = 20, p-value &lt; 2.2e-16
## 
## Model df: 4.   Total lags used: 24</code></pre>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" tabindex="-1"></a><span class="co"># Pronosticar 12 períodos (ajustado para cubrir hasta 2030)</span></span>
<span id="cb20-2"><a href="#cb20-2" tabindex="-1"></a>pronostico <span class="ot">&lt;-</span> <span class="fu">forecast</span>(modelo_arima, <span class="at">h =</span> <span class="dv">72</span>)  <span class="co"># 72 meses = 6 años</span></span>
<span id="cb20-3"><a href="#cb20-3" tabindex="-1"></a></span>
<span id="cb20-4"><a href="#cb20-4" tabindex="-1"></a><span class="co"># Graficar el pronóstico con el eje x correcto</span></span>
<span id="cb20-5"><a href="#cb20-5" tabindex="-1"></a><span class="fu">plot</span>(pronostico, <span class="at">xlab =</span> <span class="st">&quot;Año&quot;</span>, <span class="at">ylab =</span> <span class="st">&quot;Tasa&quot;</span>, <span class="at">main =</span> <span class="st">&quot;Pronóstico de Tasa&quot;</span>)</span></code></pre></div>
<p><img src="index_files/figure-html/unnamed-chunk-20-2.png" width="672" /></p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">colnames</span>(data2))</span></code></pre></div>
<pre><code>## [1] &quot;Anio&quot;          &quot;Mes&quot;           &quot;Fecha&quot;         &quot;Tasa&quot;         
## [5] &quot;PromedioMovil&quot; &quot;Tasa_lag1&quot;</code></pre>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" tabindex="-1"></a>ts_data <span class="ot">&lt;-</span> <span class="fu">ts</span>(data2[[<span class="st">&quot;Tasa&quot;</span>]], <span class="at">start =</span> <span class="fu">c</span>(<span class="dv">1999</span>, <span class="dv">1</span>), <span class="at">frequency =</span> <span class="dv">12</span>)</span>
<span id="cb23-2"><a href="#cb23-2" tabindex="-1"></a></span>
<span id="cb23-3"><a href="#cb23-3" tabindex="-1"></a></span>
<span id="cb23-4"><a href="#cb23-4" tabindex="-1"></a><span class="co"># Normal QQ Plot de los residuos</span></span>
<span id="cb23-5"><a href="#cb23-5" tabindex="-1"></a><span class="co">#residuos_diff &lt;- residuals(modelo_arima_diff)</span></span>
<span id="cb23-6"><a href="#cb23-6" tabindex="-1"></a><span class="co">#par(mfrow = c(1, 1)) </span></span>
<span id="cb23-7"><a href="#cb23-7" tabindex="-1"></a><span class="co">#qqnorm(residuos_diff, main = &quot;Normal QQ Plot de Residuos&quot;)</span></span>
<span id="cb23-8"><a href="#cb23-8" tabindex="-1"></a><span class="co">#qqline(residuos_diff, col = &quot;red&quot;)</span></span>
<span id="cb23-9"><a href="#cb23-9" tabindex="-1"></a></span>
<span id="cb23-10"><a href="#cb23-10" tabindex="-1"></a><span class="co"># Pronosticar 72 períodos (6 años)</span></span>
<span id="cb23-11"><a href="#cb23-11" tabindex="-1"></a><span class="co">#n_periods &lt;- 72</span></span>
<span id="cb23-12"><a href="#cb23-12" tabindex="-1"></a><span class="co">#pronostico_diff &lt;- forecast(modelo_arima_diff, h = n_periods)</span></span>
<span id="cb23-13"><a href="#cb23-13" tabindex="-1"></a></span>
<span id="cb23-14"><a href="#cb23-14" tabindex="-1"></a><span class="co"># Graficar el pronóstico</span></span>
<span id="cb23-15"><a href="#cb23-15" tabindex="-1"></a><span class="co">#plot(pronostico_diff, main = &quot;Pronóstico de Tasa&quot;)</span></span></code></pre></div>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" tabindex="-1"></a><span class="co"># Cargar las bibliotecas necesarias</span></span>
<span id="cb24-2"><a href="#cb24-2" tabindex="-1"></a><span class="fu">library</span>(forecast)  <span class="co"># Para el modelado ARIMA</span></span>
<span id="cb24-3"><a href="#cb24-3" tabindex="-1"></a><span class="fu">library</span>(tseries)   <span class="co"># Para funciones adicionales</span></span>
<span id="cb24-4"><a href="#cb24-4" tabindex="-1"></a><span class="fu">library</span>(ggplot2)   <span class="co"># Para gráficos</span></span>
<span id="cb24-5"><a href="#cb24-5" tabindex="-1"></a></span>
<span id="cb24-6"><a href="#cb24-6" tabindex="-1"></a><span class="co"># Verificar los nombres de las columnas en data2</span></span>
<span id="cb24-7"><a href="#cb24-7" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">colnames</span>(data2))</span></code></pre></div>
<pre><code>## [1] &quot;Anio&quot;          &quot;Mes&quot;           &quot;Fecha&quot;         &quot;Tasa&quot;         
## [5] &quot;PromedioMovil&quot; &quot;Tasa_lag1&quot;</code></pre>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" tabindex="-1"></a><span class="co"># Convertir los datos a un objeto ts, usando frecuencia mensual</span></span>
<span id="cb26-2"><a href="#cb26-2" tabindex="-1"></a>ts_data <span class="ot">&lt;-</span> <span class="fu">ts</span>(data2[[<span class="st">&quot;Tasa&quot;</span>]], <span class="at">start =</span> <span class="fu">c</span>(<span class="dv">1999</span>, <span class="dv">1</span>), <span class="at">frequency =</span> <span class="dv">12</span>)</span>
<span id="cb26-3"><a href="#cb26-3" tabindex="-1"></a></span>
<span id="cb26-4"><a href="#cb26-4" tabindex="-1"></a><span class="co"># Probar la estacionariedad de la serie original</span></span>
<span id="cb26-5"><a href="#cb26-5" tabindex="-1"></a>adf_test <span class="ot">&lt;-</span> <span class="fu">adf.test</span>(ts_data, <span class="at">alternative =</span> <span class="st">&quot;stationary&quot;</span>)</span>
<span id="cb26-6"><a href="#cb26-6" tabindex="-1"></a><span class="fu">print</span>(adf_test)</span></code></pre></div>
<pre><code>## 
##  Augmented Dickey-Fuller Test
## 
## data:  ts_data
## Dickey-Fuller = -1.15, Lag order = 6, p-value = 0.9133
## alternative hypothesis: stationary</code></pre>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" tabindex="-1"></a><span class="co"># Diferenciar la serie si no es estacionaria</span></span>
<span id="cb28-2"><a href="#cb28-2" tabindex="-1"></a>differenced_data <span class="ot">&lt;-</span> <span class="fu">diff</span>(ts_data)</span>
<span id="cb28-3"><a href="#cb28-3" tabindex="-1"></a></span>
<span id="cb28-4"><a href="#cb28-4" tabindex="-1"></a><span class="co"># Probar la estacionariedad de la serie diferenciada</span></span>
<span id="cb28-5"><a href="#cb28-5" tabindex="-1"></a>adf_test_diff <span class="ot">&lt;-</span> <span class="fu">adf.test</span>(differenced_data, <span class="at">alternative =</span> <span class="st">&quot;stationary&quot;</span>)</span>
<span id="cb28-6"><a href="#cb28-6" tabindex="-1"></a><span class="fu">print</span>(adf_test_diff)</span></code></pre></div>
<pre><code>## 
##  Augmented Dickey-Fuller Test
## 
## data:  differenced_data
## Dickey-Fuller = -3.0792, Lag order = 6, p-value = 0.1214
## alternative hypothesis: stationary</code></pre>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" tabindex="-1"></a><span class="co"># Ajustar el modelo ARIMA(0,1,3)(0,1,1)[12] si es necesario</span></span>
<span id="cb30-2"><a href="#cb30-2" tabindex="-1"></a>modelo_arima_diff <span class="ot">&lt;-</span> <span class="fu">Arima</span>(ts_data, <span class="at">order =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">3</span>), <span class="at">seasonal =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">1</span>))</span>
<span id="cb30-3"><a href="#cb30-3" tabindex="-1"></a></span>
<span id="cb30-4"><a href="#cb30-4" tabindex="-1"></a><span class="co"># Resumen del modelo ajustado</span></span>
<span id="cb30-5"><a href="#cb30-5" tabindex="-1"></a><span class="fu">summary</span>(modelo_arima_diff)</span></code></pre></div>
<pre><code>## Series: ts_data 
## ARIMA(0,1,3)(0,1,1)[12] 
## 
## Coefficients:
##          ma1     ma2     ma3     sma1
##       0.3125  0.2829  0.2279  -0.8757
## s.e.  0.0706  0.0527  0.0733   0.0470
## 
## sigma^2 = 0.1739:  log likelihood = -167.4
## AIC=344.81   AICc=345.02   BIC=363.24
## 
## Training set error measures:
##                      ME     RMSE       MAE       MPE     MAPE      MASE
## Training set 0.03580656 0.405304 0.2349259 0.6962434 4.046636 0.1116629
##                    ACF1
## Training set 0.02835974</code></pre>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" tabindex="-1"></a><span class="co"># Graficar los residuos</span></span>
<span id="cb32-2"><a href="#cb32-2" tabindex="-1"></a><span class="fu">checkresiduals</span>(modelo_arima_diff)</span></code></pre></div>
<p><img src="index_files/figure-html/unnamed-chunk-22-1.png" width="672" /></p>
<pre><code>## 
##  Ljung-Box test
## 
## data:  Residuals from ARIMA(0,1,3)(0,1,1)[12]
## Q* = 46.306, df = 20, p-value = 0.0007315
## 
## Model df: 4.   Total lags used: 24</code></pre>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" tabindex="-1"></a><span class="co"># Normal QQ Plot de los residuos</span></span>
<span id="cb34-2"><a href="#cb34-2" tabindex="-1"></a>residuos_diff <span class="ot">&lt;-</span> <span class="fu">residuals</span>(modelo_arima_diff)</span>
<span id="cb34-3"><a href="#cb34-3" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>))  <span class="co"># Asegúrate de que solo hay un gráfico en la ventana</span></span>
<span id="cb34-4"><a href="#cb34-4" tabindex="-1"></a><span class="fu">qqnorm</span>(residuos_diff, <span class="at">main =</span> <span class="st">&quot;Normal QQ Plot de Residuos&quot;</span>)</span>
<span id="cb34-5"><a href="#cb34-5" tabindex="-1"></a><span class="fu">qqline</span>(residuos_diff, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>)</span></code></pre></div>
<p><img src="index_files/figure-html/unnamed-chunk-22-2.png" width="672" /></p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" tabindex="-1"></a><span class="co"># Realizar el test de normalidad de Shapiro-Wilk</span></span>
<span id="cb35-2"><a href="#cb35-2" tabindex="-1"></a>shapiro_test <span class="ot">&lt;-</span> <span class="fu">shapiro.test</span>(residuos_diff)</span>
<span id="cb35-3"><a href="#cb35-3" tabindex="-1"></a><span class="fu">print</span>(shapiro_test)</span></code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  residuos_diff
## W = 0.7956, p-value &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" tabindex="-1"></a><span class="co"># Pronosticar 72 períodos (6 años)</span></span>
<span id="cb37-2"><a href="#cb37-2" tabindex="-1"></a>n_periods <span class="ot">&lt;-</span> <span class="dv">72</span></span>
<span id="cb37-3"><a href="#cb37-3" tabindex="-1"></a>pronostico_diff <span class="ot">&lt;-</span> <span class="fu">forecast</span>(modelo_arima_diff, <span class="at">h =</span> n_periods)</span>
<span id="cb37-4"><a href="#cb37-4" tabindex="-1"></a></span>
<span id="cb37-5"><a href="#cb37-5" tabindex="-1"></a><span class="co"># Graficar el pronóstico</span></span>
<span id="cb37-6"><a href="#cb37-6" tabindex="-1"></a><span class="fu">plot</span>(pronostico_diff, <span class="at">main =</span> <span class="st">&quot;Pronóstico de Tasa&quot;</span>)</span></code></pre></div>
<p><img src="index_files/figure-html/unnamed-chunk-22-3.png" width="672" /></p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" tabindex="-1"></a><span class="co">#install.packages(&quot;fGarch&quot;, repos = &quot;http://cran.us.r-project.org&quot;)</span></span>
<span id="cb38-2"><a href="#cb38-2" tabindex="-1"></a></span>
<span id="cb38-3"><a href="#cb38-3" tabindex="-1"></a></span>
<span id="cb38-4"><a href="#cb38-4" tabindex="-1"></a>ts_data <span class="ot">&lt;-</span> <span class="fu">ts</span>(data2[[<span class="st">&quot;Tasa&quot;</span>]], <span class="at">start =</span> <span class="fu">c</span>(<span class="dv">1999</span>, <span class="dv">1</span>), <span class="at">frequency =</span> <span class="dv">12</span>)</span>
<span id="cb38-5"><a href="#cb38-5" tabindex="-1"></a></span>
<span id="cb38-6"><a href="#cb38-6" tabindex="-1"></a>adf_test <span class="ot">&lt;-</span> <span class="fu">adf.test</span>(ts_data, <span class="at">alternative =</span> <span class="st">&quot;stationary&quot;</span>)</span>
<span id="cb38-7"><a href="#cb38-7" tabindex="-1"></a><span class="fu">print</span>(adf_test)</span></code></pre></div>
<pre><code>## 
##  Augmented Dickey-Fuller Test
## 
## data:  ts_data
## Dickey-Fuller = -1.15, Lag order = 6, p-value = 0.9133
## alternative hypothesis: stationary</code></pre>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" tabindex="-1"></a>differenced_data <span class="ot">&lt;-</span> <span class="fu">diff</span>(ts_data)</span>
<span id="cb40-2"><a href="#cb40-2" tabindex="-1"></a></span>
<span id="cb40-3"><a href="#cb40-3" tabindex="-1"></a></span>
<span id="cb40-4"><a href="#cb40-4" tabindex="-1"></a>adf_test_diff <span class="ot">&lt;-</span> <span class="fu">adf.test</span>(differenced_data, <span class="at">alternative =</span> <span class="st">&quot;stationary&quot;</span>)</span>
<span id="cb40-5"><a href="#cb40-5" tabindex="-1"></a><span class="fu">print</span>(adf_test_diff)</span></code></pre></div>
<pre><code>## 
##  Augmented Dickey-Fuller Test
## 
## data:  differenced_data
## Dickey-Fuller = -3.0792, Lag order = 6, p-value = 0.1214
## alternative hypothesis: stationary</code></pre>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" tabindex="-1"></a><span class="co"># Ajustar el modelo ARIMA(0,1,3)(0,1,1)[12]</span></span>
<span id="cb42-2"><a href="#cb42-2" tabindex="-1"></a>modelo_arima_diff <span class="ot">&lt;-</span> <span class="fu">Arima</span>(ts_data, <span class="at">order =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">3</span>), <span class="at">seasonal =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">1</span>))</span>
<span id="cb42-3"><a href="#cb42-3" tabindex="-1"></a></span>
<span id="cb42-4"><a href="#cb42-4" tabindex="-1"></a><span class="co"># Resumen del modelo ajustado</span></span>
<span id="cb42-5"><a href="#cb42-5" tabindex="-1"></a><span class="fu">summary</span>(modelo_arima_diff)</span></code></pre></div>
<pre><code>## Series: ts_data 
## ARIMA(0,1,3)(0,1,1)[12] 
## 
## Coefficients:
##          ma1     ma2     ma3     sma1
##       0.3125  0.2829  0.2279  -0.8757
## s.e.  0.0706  0.0527  0.0733   0.0470
## 
## sigma^2 = 0.1739:  log likelihood = -167.4
## AIC=344.81   AICc=345.02   BIC=363.24
## 
## Training set error measures:
##                      ME     RMSE       MAE       MPE     MAPE      MASE
## Training set 0.03580656 0.405304 0.2349259 0.6962434 4.046636 0.1116629
##                    ACF1
## Training set 0.02835974</code></pre>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" tabindex="-1"></a><span class="co"># Graficar los residuos</span></span>
<span id="cb44-2"><a href="#cb44-2" tabindex="-1"></a><span class="fu">checkresiduals</span>(modelo_arima_diff)</span></code></pre></div>
<p><img src="index_files/figure-html/unnamed-chunk-23-1.png" width="672" /></p>
<pre><code>## 
##  Ljung-Box test
## 
## data:  Residuals from ARIMA(0,1,3)(0,1,1)[12]
## Q* = 46.306, df = 20, p-value = 0.0007315
## 
## Model df: 4.   Total lags used: 24</code></pre>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" tabindex="-1"></a><span class="co"># Normal QQ Plot de los residuos</span></span>
<span id="cb46-2"><a href="#cb46-2" tabindex="-1"></a>residuos_diff <span class="ot">&lt;-</span> <span class="fu">residuals</span>(modelo_arima_diff)</span>
<span id="cb46-3"><a href="#cb46-3" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>))  </span>
<span id="cb46-4"><a href="#cb46-4" tabindex="-1"></a><span class="fu">qqnorm</span>(residuos_diff, <span class="at">main =</span> <span class="st">&quot;Normal QQ Plot de Residuos&quot;</span>)</span>
<span id="cb46-5"><a href="#cb46-5" tabindex="-1"></a><span class="fu">qqline</span>(residuos_diff, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>)</span></code></pre></div>
<p><img src="index_files/figure-html/unnamed-chunk-23-2.png" width="672" /></p>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" tabindex="-1"></a><span class="co"># Realizar el test de normalidad de Shapiro-Wilk</span></span>
<span id="cb47-2"><a href="#cb47-2" tabindex="-1"></a>shapiro_test <span class="ot">&lt;-</span> <span class="fu">shapiro.test</span>(residuos_diff)</span>
<span id="cb47-3"><a href="#cb47-3" tabindex="-1"></a><span class="fu">print</span>(shapiro_test)</span></code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  residuos_diff
## W = 0.7956, p-value &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" tabindex="-1"></a><span class="co"># Análisis de volatilidad utilizando fGarch</span></span>
<span id="cb49-2"><a href="#cb49-2" tabindex="-1"></a>garch_model <span class="ot">&lt;-</span> <span class="fu">garch</span>(residuos_diff, <span class="at">order =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>))</span></code></pre></div>
<pre><code>## 
##  ***** ESTIMATION WITH ANALYTICAL GRADIENT ***** 
## 
## 
##      I     INITIAL X(I)        D(I)
## 
##      1     1.471681e-01     1.000e+00
##      2     5.000000e-02     1.000e+00
##      3     5.000000e-02     1.000e+00
## 
##     IT   NF      F         RELDF    PRELDF    RELDX   STPPAR   D*STEP   NPRELDF
##      0    1 -1.336e+02
##      1    3 -1.502e+02  1.11e-01  1.26e-01  3.5e-01  1.9e+03  1.0e-01  1.18e+02
##      2    4 -1.536e+02  2.19e-02  8.14e-02  2.5e-01  2.2e+00  1.0e-01  7.36e+02
##      3    6 -1.606e+02  4.39e-02  3.93e-02  5.1e-02  3.9e+00  2.3e-02  4.21e+02
##      4    7 -1.657e+02  3.08e-02  6.33e-02  9.6e-02  3.9e+00  4.6e-02  4.92e+02
##      5    8 -1.708e+02  2.98e-02  4.44e-02  7.7e-02  2.0e+00  4.6e-02  1.72e+02
##      6    9 -1.763e+02  3.12e-02  3.25e-02  6.6e-02  2.0e+00  4.6e-02  1.55e+02
##      7   10 -1.833e+02  3.82e-02  5.07e-02  1.2e-01  2.0e+00  9.2e-02  6.74e+01
##      8   12 -1.842e+02  4.82e-03  1.46e-02  2.4e-02  2.0e+00  2.2e-02  2.40e+01
##      9   13 -1.867e+02  1.33e-02  1.73e-02  1.8e-02  2.0e+00  2.2e-02  1.28e+01
##     10   16 -1.936e+02  3.54e-02  9.56e-02  1.9e-01  2.0e+00  2.5e-01  1.21e+01
##     11   21 -1.978e+02  2.13e-02  6.13e-02  1.1e-02  3.1e+00  1.2e-02  3.57e-01
##     12   22 -1.981e+02  1.79e-03  1.32e-03  9.3e-03  2.0e+00  1.2e-02  7.32e-03
##     13   23 -1.983e+02  6.06e-04  8.60e-04  7.5e-03  2.0e+00  1.2e-02  3.02e-02
##     14   26 -1.984e+02  7.73e-04  1.10e-03  3.7e-02  1.8e+00  5.4e-02  1.40e-02
##     15   27 -1.985e+02  6.45e-04  1.26e-03  4.7e-02  1.5e+00  5.4e-02  5.86e-03
##     16   29 -1.986e+02  6.98e-05  1.39e-04  1.2e-02  9.5e-01  1.8e-02  2.86e-04
##     17   30 -1.986e+02  4.70e-05  6.56e-05  1.1e-02  6.4e-01  1.8e-02  7.84e-05
##     18   32 -1.986e+02  9.40e-07  4.03e-06  3.0e-03  7.1e-01  4.4e-03  5.67e-06
##     19   35 -1.986e+02  2.06e-07  5.00e-07  5.0e-04  1.4e+00  7.4e-04  1.80e-06
##     20   38 -1.986e+02  9.89e-08  1.38e-07  1.6e-04  1.8e+00  2.4e-04  1.34e-06
##     21   41 -1.986e+02  2.63e-08  4.21e-08  5.6e-05  1.9e+00  8.2e-05  1.22e-06
##     22   53 -1.986e+02  4.29e-16  3.48e-18  3.0e-15  6.7e+08  4.9e-15  1.18e-06
##     23   54 -1.986e+02 -7.16e-16  6.95e-18  5.9e-15  3.3e+08  9.8e-15  1.18e-06
## 
##  ***** FALSE CONVERGENCE *****
## 
##  FUNCTION    -1.985695e+02   RELDX        5.909e-15
##  FUNC. EVALS      54         GRAD. EVALS      23
##  PRELDF       6.954e-18      NPRELDF      1.176e-06
## 
##      I      FINAL X(I)        D(I)          G(I)
## 
##      1    2.417150e-02     1.000e+00     9.607e-02
##      2    5.671540e-01     1.000e+00     5.482e-02
##      3    4.193714e-01     1.000e+00    -8.692e-02</code></pre>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" tabindex="-1"></a><span class="fu">summary</span>(garch_model)</span></code></pre></div>
<pre><code>## 
## Call:
## garch(x = residuos_diff, order = c(1, 1))
## 
## Model:
## GARCH(1,1)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -4.45689 -0.39305  0.05776  0.43589  5.18143 
## 
## Coefficient(s):
##     Estimate  Std. Error  t value Pr(&gt;|t|)    
## a0  0.024172    0.003891    6.212 5.25e-10 ***
## a1  0.567154    0.080415    7.053 1.75e-12 ***
## b1  0.419371    0.071239    5.887 3.94e-09 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Diagnostic Tests:
##  Jarque Bera Test
## 
## data:  Residuals
## X-squared = 390.33, df = 2, p-value &lt; 2.2e-16
## 
## 
##  Box-Ljung test
## 
## data:  Squared.Residuals
## X-squared = 0.11988, df = 1, p-value = 0.7292</code></pre>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" tabindex="-1"></a><span class="co"># Resumen de los residuos</span></span>
<span id="cb53-2"><a href="#cb53-2" tabindex="-1"></a>residuos_summary <span class="ot">&lt;-</span> <span class="fu">summary</span>(residuos_diff)</span>
<span id="cb53-3"><a href="#cb53-3" tabindex="-1"></a><span class="fu">print</span>(residuos_summary)</span></code></pre></div>
<pre><code>##     Min.  1st Qu.   Median     Mean  3rd Qu.     Max. 
## -1.45643 -0.11092  0.01333  0.03581  0.14946  3.48249</code></pre>
</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>


    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/USERNAME/REPO/edit/BRANCH/%s",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": false,
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
